Add missing #includes to fix compiler warnings.
Fixes the following warnings:
../../src/glint_driver.c: In function 'GLINTScreenInit':
../../src/glint_driver.c:2968: warning: implicit declaration of function 'cfb8_32ScreenInit'
../../src/glint_driver.c:3147: warning: implicit declaration of function 'xf86Overlay8Plus32Init'
../../src/pm2_video.c: In function 'StopVideoStream':
../../src/pm2_video.c:1339: warning: implicit declaration of function 'usleep'
../../src/pm2_video.c: In function 'xvipcHandshake':
../../src/pm2_video.c:2413: warning: implicit declaration of function 'ioctl'
../../src/pm2_video.c: In function 'xvipcOpen':
../../src/pm2_video.c:2622: warning: implicit declaration of function 'close'